/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateEventTypeRequest } from '../../models/create-event-type-request';
import { ErrorResponse } from '../../models/error-response';
import { EventType } from '../../models/event-type';

export interface AdminEventTypesCreate$Params {
      body: CreateEventTypeRequest
}

export function adminEventTypesCreate(http: HttpClient, rootUrl: string, params: AdminEventTypesCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<(EventType | ErrorResponse)>> {
  const rb = new RequestBuilder(rootUrl, adminEventTypesCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(EventType | ErrorResponse)>;
    })
  );
}

adminEventTypesCreate.PATH = '/api/admin/event-types';
