/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ErrorResponse } from '../../models/error-response';

export interface AdminEventTypesDelete$Params {
  id: string;
}

export function adminEventTypesDelete(http: HttpClient, rootUrl: string, params: AdminEventTypesDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<ErrorResponse>> {
  const rb = new RequestBuilder(rootUrl, adminEventTypesDelete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ErrorResponse>;
    })
  );
}

adminEventTypesDelete.PATH = '/api/admin/event-types/{id}';
