/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ErrorResponse } from '../../models/error-response';
import { Slot } from '../../models/slot';

export interface GuestSlotsList$Params {
  id: string;
  date: string;
}

export function guestSlotsList(http: HttpClient, rootUrl: string, params: GuestSlotsList$Params, context?: HttpContext): Observable<StrictHttpResponse<(Array<Slot> | ErrorResponse)>> {
  const rb = new RequestBuilder(rootUrl, guestSlotsList.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('date', params.date, {"explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(Array<Slot> | ErrorResponse)>;
    })
  );
}

guestSlotsList.PATH = '/api/event-types/{id}/slots';
