/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Booking } from '../../models/booking';
import { CreateBookingRequest } from '../../models/create-booking-request';
import { ErrorResponse } from '../../models/error-response';

export interface GuestBookingsCreate$Params {
      body: CreateBookingRequest
}

export function guestBookingsCreate(http: HttpClient, rootUrl: string, params: GuestBookingsCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<(Booking | ErrorResponse)>> {
  const rb = new RequestBuilder(rootUrl, guestBookingsCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(Booking | ErrorResponse)>;
    })
  );
}

guestBookingsCreate.PATH = '/api/bookings';
