openapi: 3.0.0
info:
  title: Calendar Booking API
  version: 0.0.0
tags: []
paths:
  /api/admin/bookings:
    get:
      operationId: AdminBookings_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
  /api/admin/event-types:
    get:
      operationId: AdminEventTypes_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventType'
    post:
      operationId: AdminEventTypes_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/EventType'
                  - $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventTypeRequest'
  /api/admin/event-types/{id}:
    put:
      operationId: AdminEventTypes_update
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/EventType'
                  - $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventTypeRequest'
    delete:
      operationId: AdminEventTypes_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /api/bookings:
    post:
      operationId: GuestBookings_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/Booking'
                  - $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingRequest'
  /api/event-types:
    get:
      operationId: GuestEventTypes_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventType'
  /api/event-types/{id}:
    get:
      operationId: GuestEventTypes_getEventType
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/EventType'
                  - $ref: '#/components/schemas/ErrorResponse'
  /api/event-types/{id}/slots:
    get:
      operationId: GuestSlots_list
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: date
          in: query
          required: true
          schema:
            type: string
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                anyOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/Slot'
                  - $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Booking:
      type: object
      required:
        - id
        - eventTypeId
        - guestName
        - guestEmail
        - startTime
        - endTime
        - createdAt
      properties:
        id:
          type: string
        eventTypeId:
          type: string
        guestName:
          type: string
        guestEmail:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
    CreateBookingRequest:
      type: object
      required:
        - eventTypeId
        - guestName
        - guestEmail
        - startTime
      properties:
        eventTypeId:
          type: string
        guestName:
          type: string
        guestEmail:
          type: string
          format: email
        startTime:
          type: string
          format: date-time
    CreateEventTypeRequest:
      type: object
      required:
        - title
        - description
        - duration
      properties:
        title:
          type: string
        description:
          type: string
        duration:
          type: integer
          format: int32
          minimum: 1
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    EventType:
      type: object
      required:
        - id
        - title
        - description
        - duration
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        duration:
          type: integer
          format: int32
    Slot:
      type: object
      required:
        - startTime
        - endTime
      properties:
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    UpdateEventTypeRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        duration:
          type: integer
          format: int32
          minimum: 1
