/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Booking {
  createdAt: string;
  endTime: string;
  eventTypeId: string;
  guestEmail: string;
  guestName: string;
  id: string;
  startTime: string;
}
