/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateBookingRequest {
  eventTypeId: string;
  guestEmail: string;
  guestName: string;
  startTime: string;
}
