/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdminBookingsList$Params as AdminBookingsList$Params } from './fn/operations/admin-bookings-list';
export { adminBookingsList as adminBookingsList } from './fn/operations/admin-bookings-list';
export type { AdminEventTypesList$Params as AdminEventTypesList$Params } from './fn/operations/admin-event-types-list';
export { adminEventTypesList as adminEventTypesList } from './fn/operations/admin-event-types-list';
export type { AdminEventTypesCreate$Params as AdminEventTypesCreate$Params } from './fn/operations/admin-event-types-create';
export { adminEventTypesCreate as adminEventTypesCreate } from './fn/operations/admin-event-types-create';
export type { AdminEventTypesUpdate$Params as AdminEventTypesUpdate$Params } from './fn/operations/admin-event-types-update';
export { adminEventTypesUpdate as adminEventTypesUpdate } from './fn/operations/admin-event-types-update';
export type { AdminEventTypesDelete$Params as AdminEventTypesDelete$Params } from './fn/operations/admin-event-types-delete';
export { adminEventTypesDelete as adminEventTypesDelete } from './fn/operations/admin-event-types-delete';
export type { GuestBookingsCreate$Params as GuestBookingsCreate$Params } from './fn/operations/guest-bookings-create';
export { guestBookingsCreate as guestBookingsCreate } from './fn/operations/guest-bookings-create';
export type { GuestEventTypesList$Params as GuestEventTypesList$Params } from './fn/operations/guest-event-types-list';
export { guestEventTypesList as guestEventTypesList } from './fn/operations/guest-event-types-list';
export type { GuestEventTypesGetEventType$Params as GuestEventTypesGetEventType$Params } from './fn/operations/guest-event-types-get-event-type';
export { guestEventTypesGetEventType as guestEventTypesGetEventType } from './fn/operations/guest-event-types-get-event-type';
export type { GuestSlotsList$Params as GuestSlotsList$Params } from './fn/operations/guest-slots-list';
export { guestSlotsList as guestSlotsList } from './fn/operations/guest-slots-list';
