/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Booking } from './models/booking';
export type { CreateBookingRequest } from './models/create-booking-request';
export type { CreateEventTypeRequest } from './models/create-event-type-request';
export type { ErrorResponse } from './models/error-response';
export type { EventType } from './models/event-type';
export type { Slot } from './models/slot';
export type { UpdateEventTypeRequest } from './models/update-event-type-request';
